/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movimentacao;

import Banco.Banco;
import Banco.BancoFuncoes;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class DemonstrativoVenda extends javax.swing.JFrame {

    BancoFuncoes bf = new BancoFuncoes();
    Banco ba = new Banco();
    
    public DemonstrativoVenda() {
        initComponents();
        
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        this.setLocationRelativeTo(null);  
        
        
         gridDemo.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"Produtos","Qtde","Preco","Total"}) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }}); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridDemo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPagamento = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtValorVenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setText("Valor da Venda:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 50, 90, 30);

        jLabel4.setText("Cliente:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 90, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));
        jPanel2.setLayout(null);

        gridDemo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod", "Produto", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(gridDemo);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 450, 170);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 90, 470, 200);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));
        jPanel1.setLayout(null);

        tabelaPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "pag", "Tipo", "Valor", "#"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPagamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaPagamento);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 210, 210);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(490, 50, 230, 240);

        jLabel2.setText("Data da Venda:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 10, 90, 30);

        jButton1.setText("Imprimir Cupon");
        jButton1.setEnabled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(553, 300, 110, 30);

        txtData.setEditable(false);
        getContentPane().add(txtData);
        txtData.setBounds(570, 10, 120, 30);

        txtCliente.setEditable(false);
        getContentPane().add(txtCliente);
        txtCliente.setBounds(110, 10, 150, 30);

        txtValorVenda.setEditable(false);
        getContentPane().add(txtValorVenda);
        txtValorVenda.setBounds(110, 50, 150, 30);

        setBounds(0, 0, 730, 396);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPagamentoMouseClicked
       
    }//GEN-LAST:event_tabelaPagamentoMouseClicked

    
    public void carregaTabela(String npedido){
       
        String msg1 = "Produtos recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Produtos";
        String vsql = "SELECT produto,qtde,preco,total FROM itensPedido where npedido = "+npedido+"";


        bf.tabelaDemonstrativo(vsql, msg1, msg2, gridDemo);
  
    }
    
    public void buscaVenda(String npedido){
        
           ResultSet rs;

        

            rs = ba.buscaVendaDemo(npedido);
            try {
                               
                if (ba.buscaVendaDemo(npedido) != null) {
               
                    System.out.println("aaaaaaaaaaaa");

                    txtCliente.setText(rs.getString("c.nome"));
                    txtValorVenda.setText(rs.getString("v.total"));
                    txtData.setText(rs.getString("v.data"));
                 

                }

                else{
                        System.out.println("null");
                  
                }
            } catch (SQLException ex) {
            }
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemonstrativoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemonstrativoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemonstrativoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemonstrativoVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemonstrativoVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable gridDemo;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tabelaPagamento;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
