/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Funcionario;

import Banco.Banco;
import Banco.BancoCep;
import Funcoes.LimitarCampos;
import Funcoes.ValidaCnpj;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.alfredlibrary.validadores.CPF;

/**
 *
 * @author Usuario
 */
public class Funcionario extends javax.swing.JPanel {

    Banco ba = new Banco();
    BancoCep bacep = new BancoCep();
    public Funcionario() {
        initComponents();
        
         txt_cpfFun.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCpf(evt);  
              }  
          });
         
         txt_cepFun.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCep(evt);  
              }  
          });  
         
         
         
         
        txt_setorFun.setDocument(new LimitarCampos(21));
        txt_nomeFun.setDocument(new LimitarCampos(55));
        txt_cepFun.setDocument(new LimitarCampos(8));
        txt_estadoFun.setDocument(new LimitarCampos(2));
        txt_cidadeFun.setDocument(new LimitarCampos(32));
        txt_bairroFun.setDocument(new LimitarCampos(40));
        txt_endeFun.setDocument(new LimitarCampos(60));
        txt_compleFun.setDocument(new LimitarCampos(50));
        txt_numFun.setDocument(new LimitarCampos(6));
        txt_loginFun.setDocument(new LimitarCampos(15));
        txt_senhaFun.setDocument(new LimitarCampos(15));
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalUsuario = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton15 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton16 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton18 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jButton19 = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jButton20 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txt_loginFun = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_senhaFun = new javax.swing.JPasswordField();
        CriarAcesso = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Caixa = new javax.swing.JCheckBox();
        Adm = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_estadoFun = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_bairroFun = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_endeFun = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_compleFun = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_cepFun = new javax.swing.JFormattedTextField();
        txt_numFun = new javax.swing.JFormattedTextField();
        txt_cidadeFun = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txt_celFun = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_telFun = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_cpfFun = new javax.swing.JFormattedTextField();
        txt_nomeFun = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_rgFun = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_setorFun = new javax.swing.JTextField();
        cmb_sexoFun = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_nasciFun = new javax.swing.JFormattedTextField();

        setLayout(null);

        internalUsuario.setClosable(true);
        internalUsuario.setVisible(true);

        jPanel2.setLayout(null);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        jButton15.setText("Limpar Campos");
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton15);
        jToolBar2.add(jSeparator1);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        jButton16.setText("Gravar");
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton16);
        jToolBar2.add(jSeparator7);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        jButton18.setText("Alterar");
        jButton18.setFocusable(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton18);
        jToolBar2.add(jSeparator10);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton19.setText("Excluir");
        jButton19.setFocusable(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton19);
        jToolBar2.add(jSeparator16);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        jButton20.setText("Pesquisar");
        jButton20.setFocusable(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton20);

        jPanel2.add(jToolBar2);
        jToolBar2.setBounds(10, 0, 790, 80);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário e Senha"));
        jPanel4.setLayout(null);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("Login:");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(10, 30, 50, 30);
        jPanel4.add(txt_loginFun);
        txt_loginFun.setBounds(70, 30, 140, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("Senha:");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(10, 80, 50, 30);
        jPanel4.add(txt_senhaFun);
        txt_senhaFun.setBounds(70, 80, 140, 30);

        CriarAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/registro.png"))); // NOI18N
        CriarAcesso.setText("Criar Acesso");
        CriarAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarAcessoActionPerformed(evt);
            }
        });
        jPanel4.add(CriarAcesso);
        CriarAcesso.setBounds(40, 220, 180, 40);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Permissões"));
        jPanel8.setLayout(null);

        Caixa.setText("Caixa");
        jPanel8.add(Caixa);
        Caixa.setBounds(30, 20, 130, 23);

        Adm.setText("Administração");
        jPanel8.add(Adm);
        Adm.setBounds(30, 50, 130, 23);

        jPanel4.add(jPanel8);
        jPanel8.setBounds(40, 120, 180, 90);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(580, 90, 240, 290);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        jPanel5.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Cep:");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(10, 30, 40, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("UF:");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(150, 30, 40, 30);
        jPanel5.add(txt_estadoFun);
        txt_estadoFun.setBounds(180, 30, 40, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("Cidade: ");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(250, 30, 50, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Bairro: ");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(10, 90, 50, 30);
        jPanel5.add(txt_bairroFun);
        txt_bairroFun.setBounds(50, 90, 250, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Endereço:");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(10, 140, 70, 30);
        jPanel5.add(txt_endeFun);
        txt_endeFun.setBounds(80, 140, 360, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("N°:");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(450, 140, 40, 30);
        jPanel5.add(txt_compleFun);
        txt_compleFun.setBounds(120, 180, 320, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Complemento: ");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 180, 100, 30);

        try {
            txt_cepFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txt_cepFun);
        txt_cepFun.setBounds(40, 30, 100, 30);

        try {
            txt_numFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txt_numFun);
        txt_numFun.setBounds(470, 140, 70, 30);
        jPanel5.add(txt_cidadeFun);
        txt_cidadeFun.setBounds(290, 30, 240, 30);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 280, 550, 220);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));
        jPanel7.setLayout(null);

        try {
            txt_celFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel7.add(txt_celFun);
        txt_celFun.setBounds(70, 60, 140, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Celular: ");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(10, 60, 80, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Telefone: ");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(10, 20, 80, 30);

        try {
            txt_telFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel7.add(txt_telFun);
        txt_telFun.setBounds(70, 20, 140, 30);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 500, 550, 110);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoal"));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("CPF:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(20, 20, 40, 30);

        try {
            txt_cpfFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_cpfFun);
        txt_cpfFun.setBounds(60, 20, 140, 30);
        jPanel6.add(txt_nomeFun);
        txt_nomeFun.setBounds(60, 100, 370, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Nome:");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(20, 100, 50, 30);

        try {
            txt_rgFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_rgFun);
        txt_rgFun.setBounds(60, 60, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("RG:");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(20, 60, 40, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Setor:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(240, 60, 50, 30);

        txt_setorFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_setorFunActionPerformed(evt);
            }
        });
        jPanel6.add(txt_setorFun);
        txt_setorFun.setBounds(280, 60, 140, 30);

        cmb_sexoFun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino" }));
        jPanel6.add(cmb_sexoFun);
        cmb_sexoFun.setBounds(280, 20, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Sexo:");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(240, 20, 50, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Data de nascimento: ");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(10, 140, 130, 30);

        try {
            txt_nasciFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_nasciFun);
        txt_nasciFun.setBounds(130, 140, 80, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 90, 550, 180);

        javax.swing.GroupLayout internalUsuarioLayout = new javax.swing.GroupLayout(internalUsuario.getContentPane());
        internalUsuario.getContentPane().setLayout(internalUsuarioLayout);
        internalUsuarioLayout.setHorizontalGroup(
            internalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
            .addGroup(internalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(internalUsuarioLayout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        internalUsuarioLayout.setVerticalGroup(
            internalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
            .addGroup(internalUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
        );

        add(internalUsuario);
        internalUsuario.setBounds(0, 0, 860, 690);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        String aux,nomeFun, nasciFun, endeFun, compleFun, bairroFun , cidadeFun, setorFun, loginFun, senhaFun, sexoFun,
        rgFun, cpfFun, cepFun, numFun,ufFun, telFun, celFun, permissao = "";

      
       
        nomeFun = txt_nomeFun.getText();
        nasciFun = txt_nasciFun.getText();
        endeFun = txt_endeFun.getText();
        compleFun = txt_compleFun.getText();
        bairroFun = txt_bairroFun.getText();
        ufFun = txt_estadoFun.getText();
        cidadeFun = txt_cidadeFun.getText();
        setorFun = txt_setorFun.getText();
        rgFun = txt_rgFun.getText();
        cpfFun = txt_cpfFun.getText();
        cepFun = txt_cepFun.getText();
        numFun = txt_numFun.getText();
        telFun = txt_telFun.getText();
        celFun = txt_celFun.getText();

        sexoFun = cmb_sexoFun.getSelectedItem().toString();
        System.out.println(sexoFun);

         if (CPF.isValido(cpfFun) == false || "111.111.111-11".equals(cpfFun) || "000.000.000-00".equals(cpfFun) || "   .   .   -  ".equals(cpfFun)  ){
         
             JOptionPane.showMessageDialog(null, "Cpf Invalido");
             
             
         }
        
             else {
             
             ba.gravaFuncionario(nomeFun, nasciFun, endeFun, compleFun, bairroFun , cidadeFun, setorFun, sexoFun, rgFun, cpfFun, cepFun, numFun, telFun, celFun,ufFun);

            txt_nomeFun.setText("");
            txt_cpfFun.setText("");
            txt_rgFun.setText("");
            txt_nasciFun.setText("");
            txt_endeFun.setText("");
            txt_compleFun.setText("");
            txt_bairroFun.setText("");
            txt_cepFun.setText("");
            txt_numFun.setText("");
            txt_telFun.setText("");
            txt_celFun.setText("");
            txt_setorFun.setText("");
            txt_cidadeFun.setText("");
            txt_estadoFun.setText("");
         
        }
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

    }//GEN-LAST:event_jButton18ActionPerformed

    private void CriarAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarAcessoActionPerformed
        String loginFun,senhaFun, permissao = "";

        loginFun = txt_loginFun.getText();
        senhaFun = txt_senhaFun.getText();

        if (Caixa.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }

        if (Adm.isSelected()) {
            permissao += "1";
        } else {
            permissao += "0";
        }


        if (ba.gravaLogin( loginFun, senhaFun, permissao)) {

            txt_loginFun.setText("");
            txt_senhaFun.setText("");

        }
    }//GEN-LAST:event_CriarAcessoActionPerformed

    private void txt_setorFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_setorFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_setorFunActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
          //String nomeFantasia = nome_fantasiaFor.getText();
        
       
            
             
        String cpf =txt_cpfFun.getText();

        if(CPF.isValido(cpf) == false ||"   .   .   -  ".equals(cpf)){

            JOptionPane.showMessageDialog(null,"Preencha o campo CPF  corretamente para realizar uma exclusão");
            
            txt_cpfFun.requestFocus();

        }

        else{
            if (ba.excluiUsuario(cpf)) {
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");

             txt_nomeFun.setText("");
            txt_cpfFun.setText("");
            txt_rgFun.setText("");
            txt_nasciFun.setText("");
            txt_endeFun.setText("");
            txt_compleFun.setText("");
            txt_bairroFun.setText("");
            txt_cepFun.setText("");
            txt_numFun.setText("");
            txt_telFun.setText("");
            txt_celFun.setText("");
            txt_setorFun.setText("");
            txt_cidadeFun.setText("");
            txt_estadoFun.setText("");

            }
            else {
                JOptionPane.showMessageDialog(null, "Não encontrado");
            }
        }
        
        
        
         
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
         ResultSet rs;

        
        String cpf = txt_cpfFun.getText();
        
       

        
        if("   .   .   -  ".equals(cpf)){

            JOptionPane.showMessageDialog(null,"Preencha o campo Cpf para realizar uma busca");
            txt_cpfFun.requestFocus();
        }

        else{

            rs = ba.buscaFuncionario(cpf);
            try {

                if (ba.buscaFuncionario(cpf) != null) {
                    txt_rgFun.setText(rs.getString("rgFun"));
                    txt_nomeFun.setText(rs.getString("nomeFun"));
                    txt_setorFun.setText(rs.getString("setorFun"));
                    txt_nasciFun.setText(rs.getString("nasciFun"));
                    txt_cepFun.setText(rs.getString("cepFun"));
                    txt_estadoFun.setText(rs.getString("ufFun"));
                    txt_cidadeFun.setText(rs.getString("cidadeFun"));
                    txt_bairroFun.setText(rs.getString("bairroFun"));
                    txt_endeFun.setText(rs.getString("endeFun"));
                    txt_compleFun.setText(rs.getString("compleFun"));
                    txt_numFun.setText(rs.getString("numFun"));
                    txt_cpfFun.setText(txt_cpfFun.getText());
                    txt_telFun.setText(rs.getString("telFun"));
                     txt_celFun.setText(rs.getString("celFun"));    

                }
                else{

                    txt_rgFun.setText("");
                    txt_nomeFun.setText("");
                    txt_setorFun.setText("");
                    txt_nasciFun.setText("");
                    txt_cepFun.setText("");
                    txt_estadoFun.setText("");
                    txt_cidadeFun.setText("");
                    txt_bairroFun.setText("");
                    txt_endeFun.setText("");
                    txt_compleFun.setText("");
                    txt_numFun.setText("");
                    txt_cpfFun.setText("");
                    txt_telFun.setText("");
                     txt_celFun.setText("");   
                }
            } catch (SQLException ex) {
            }
        }
        
        
    
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
            txt_nomeFun.setText("");
            txt_cpfFun.setText("");
            txt_rgFun.setText("");
            txt_nasciFun.setText("");
            txt_endeFun.setText("");
            txt_compleFun.setText("");
            txt_bairroFun.setText("");
            txt_cepFun.setText("");
            txt_numFun.setText("");
            txt_telFun.setText("");
            txt_celFun.setText("");
            txt_setorFun.setText("");
            txt_cidadeFun.setText("");
            txt_estadoFun.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    
    
      private void jTextField1FocusLostCpf(java.awt.event.FocusEvent evt) {
        String cpfFor = txt_cpfFun.getText();
        String cpf = cpfFor;

            if (CPF.isValido(cpfFor) == false || "111.111.111-11".equals(cpfFor) || "000.000.000-00".equals(cpfFor) || "   .   .   -  ".equals(cpfFor)  ){


          

          JOptionPane.showMessageDialog(null,"Atenção Cpf inválido");
          
          txt_cpfFun.requestFocus();
          
          
         }
        else{
         
         ValidaCnpj.formatar(cpf);
         txt_cpfFun.setText(cpf);
         System.out.println(cpf);
         
        }

    }

      
      
       private void jTextField1FocusLostCep(java.awt.event.FocusEvent evt) {  
        ResultSet rs;

        String cep = txt_cepFun.getText();

        if("".equals(cep)){

        }

        
        else{
            
            
            rs = bacep.buscaCep(cep);
            try {

                if (bacep.buscaCep(cep) != null) {

                    txt_endeFun.setText(rs.getString("desc_logradouro"));
                    txt_cidadeFun.setText(rs.getString("desc_cidade"));
                    txt_estadoFun.setText(rs.getString("flg_estado"));
                    txt_bairroFun.setText(rs.getString("desc_bairro"));
                    
                }
                else{

                }
            } catch (SQLException ex) {
            }
        } 
        
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Adm;
    private javax.swing.JCheckBox Caixa;
    private javax.swing.JButton CriarAcesso;
    private javax.swing.JComboBox cmb_sexoFun;
    public javax.swing.JInternalFrame internalUsuario;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JFormattedTextField txt_bairroFun;
    private javax.swing.JFormattedTextField txt_celFun;
    private javax.swing.JFormattedTextField txt_cepFun;
    private javax.swing.JTextField txt_cidadeFun;
    private javax.swing.JFormattedTextField txt_compleFun;
    private javax.swing.JFormattedTextField txt_cpfFun;
    private javax.swing.JFormattedTextField txt_endeFun;
    private javax.swing.JTextField txt_estadoFun;
    private javax.swing.JTextField txt_loginFun;
    private javax.swing.JFormattedTextField txt_nasciFun;
    private javax.swing.JFormattedTextField txt_nomeFun;
    private javax.swing.JFormattedTextField txt_numFun;
    private javax.swing.JFormattedTextField txt_rgFun;
    private javax.swing.JPasswordField txt_senhaFun;
    private javax.swing.JTextField txt_setorFun;
    private javax.swing.JFormattedTextField txt_telFun;
    // End of variables declaration//GEN-END:variables
}
