/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Funcionario;

import Banco.Banco;
import Banco.BancoCep;
import BancoObjeto.ObjetoCliente;
import BancoObjeto.ObjetoFuncionario;
import Funcoes.LimitarCampos;
import Funcoes.ValidaCnpj;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.alfredlibrary.validadores.CPF;

/**
 *
 * @author Usuario
 */
public class Funcionario extends javax.swing.JPanel {

    
    Banco ba = new Banco();
    BancoCep bacep = new BancoCep();
    public Funcionario() {
        initComponents();
        
        
        
        // BLOQUEA A EDIÇÃO DA JTABLE
        gridFuncionario.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"Nome", "Sexo", "CPF", "RG", "Data Nascimento", "UF", "Cidade", "Endereco", "Bairro", "Cep", "Numero", "Complemento", "Telefone", "Ceular", "Setor" }) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }}); 
          
        
        
        
        
        
         txt_cpfFun.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCpf(evt);  
              }  
          });
         
         txt_cepFun.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCep(evt);  
              }  
          });  
         
         
         
         
        txt_setorFun.setDocument(new LimitarCampos(21));
        txt_nomeFun.setDocument(new LimitarCampos(55));
        txt_cepFun.setDocument(new LimitarCampos(8));
        txt_estadoFun.setDocument(new LimitarCampos(2));
        txt_cidadeFun.setDocument(new LimitarCampos(32));
        txt_bairroFun.setDocument(new LimitarCampos(40));
        txt_endeFun.setDocument(new LimitarCampos(60));
        txtCompleFun.setDocument(new LimitarCampos(50));
        txtNumFun.setDocument(new LimitarCampos(6));

        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFuncionario = new javax.swing.JInternalFrame();
        TabFuncionario = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton15 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton16 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnAlterarFuncionario = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jButton19 = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jButton20 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_estadoFun = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_bairroFun = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_endeFun = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_cepFun = new javax.swing.JFormattedTextField();
        txt_cidadeFun = new javax.swing.JTextField();
        txtNumFun = new javax.swing.JTextField();
        txtCompleFun = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txt_celFun = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_telFun = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_cpfFun = new javax.swing.JFormattedTextField();
        txt_nomeFun = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_rgFun = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_setorFun = new javax.swing.JTextField();
        cmb_sexoFun = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_nasciFun = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridFuncionario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JFormattedTextField();

        setLayout(null);

        internalFuncionario.setClosable(true);
        internalFuncionario.setVisible(true);
        internalFuncionario.getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        jButton15.setText("Limpar Campos");
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton15);
        jToolBar2.add(jSeparator1);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        jButton16.setText("Gravar");
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton16);
        jToolBar2.add(jSeparator7);

        btnAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        btnAlterarFuncionario.setText("Alterar");
        btnAlterarFuncionario.setFocusable(false);
        btnAlterarFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterarFuncionario.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnAlterarFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFuncionarioActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAlterarFuncionario);
        jToolBar2.add(jSeparator10);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton19.setText("Excluir");
        jButton19.setFocusable(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton19);
        jToolBar2.add(jSeparator16);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        jButton20.setText("Pesquisar");
        jButton20.setFocusable(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton20);

        jPanel2.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 790, 80);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        jPanel5.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Cep:");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(10, 30, 40, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("UF:");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(150, 30, 40, 30);
        jPanel5.add(txt_estadoFun);
        txt_estadoFun.setBounds(180, 30, 40, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("Cidade: ");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(10, 90, 50, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Bairro: ");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(310, 90, 50, 30);
        jPanel5.add(txt_bairroFun);
        txt_bairroFun.setBounds(350, 90, 250, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Endereço:");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(10, 140, 70, 30);
        jPanel5.add(txt_endeFun);
        txt_endeFun.setBounds(100, 140, 340, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("N°:");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(450, 140, 40, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Complemento: ");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 180, 100, 30);

        try {
            txt_cepFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txt_cepFun);
        txt_cepFun.setBounds(40, 30, 100, 30);
        jPanel5.add(txt_cidadeFun);
        txt_cidadeFun.setBounds(60, 90, 230, 30);
        jPanel5.add(txtNumFun);
        txtNumFun.setBounds(480, 140, 80, 30);
        jPanel5.add(txtCompleFun);
        txtCompleFun.setBounds(100, 180, 300, 30);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 270, 1030, 220);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));
        jPanel7.setLayout(null);

        try {
            txt_celFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel7.add(txt_celFun);
        txt_celFun.setBounds(300, 20, 140, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Celular: ");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(250, 20, 80, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Telefone: ");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(10, 20, 80, 30);

        try {
            txt_telFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel7.add(txt_telFun);
        txt_telFun.setBounds(70, 20, 140, 30);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 500, 1030, 80);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoal"));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("CPF:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(20, 20, 40, 30);

        try {
            txt_cpfFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_cpfFun);
        txt_cpfFun.setBounds(60, 20, 140, 30);
        jPanel6.add(txt_nomeFun);
        txt_nomeFun.setBounds(60, 70, 370, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Nome:");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(20, 70, 50, 30);

        try {
            txt_rgFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_rgFun);
        txt_rgFun.setBounds(280, 20, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("RG:");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(240, 20, 40, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Setor:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(240, 120, 50, 30);

        txt_setorFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_setorFunActionPerformed(evt);
            }
        });
        jPanel6.add(txt_setorFun);
        txt_setorFun.setBounds(280, 120, 140, 30);

        cmb_sexoFun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Feminino", "Masculino" }));
        cmb_sexoFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sexoFunActionPerformed(evt);
            }
        });
        jPanel6.add(cmb_sexoFun);
        cmb_sexoFun.setBounds(500, 70, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Sexo:");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(450, 70, 50, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Data de nascimento: ");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(20, 120, 130, 30);

        try {
            txt_nasciFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_nasciFun);
        txt_nasciFun.setBounds(140, 120, 80, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 90, 1030, 180);

        TabFuncionario.addTab("Registro", jPanel2);

        jPanel1.setLayout(null);

        gridFuncionario.setAutoCreateRowSorter(true);
        gridFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "CPF", "RG", "Data Nascimento", "UF", "Cidade", "Endereco", "Bairro", "Cep", "Numero", "Complemento", "Telefone", "Celular", "Setor"
            }
        ));
        gridFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridFuncionario);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 1040, 400);

        jLabel1.setText("CPF:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 50, 50, 40);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisa);
        btnPesquisa.setBounds(370, 40, 180, 50);

        try {
            txtPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtPesquisa);
        txtPesquisa.setBounds(180, 50, 130, 30);

        TabFuncionario.addTab("Pesquisa", jPanel1);

        internalFuncionario.getContentPane().add(TabFuncionario);
        TabFuncionario.setBounds(0, 0, 1060, 630);

        add(internalFuncionario);
        internalFuncionario.setBounds(0, 0, 1090, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        String aux,nomeFun, nasciFun, endeFun, compleFun, bairroFun , cidadeFun, setorFun, loginFun, senhaFun, sexoFun,
        rgFun, cpfFun, cepFun, numFun,ufFun, telFun, celFun, permissao = "";

       
        nomeFun = txt_nomeFun.getText();
        nasciFun = txt_nasciFun.getText();
        endeFun = txt_endeFun.getText();
        compleFun = txtCompleFun.getText();
        bairroFun = txt_bairroFun.getText();
        ufFun = txt_estadoFun.getText();
        cidadeFun = txt_cidadeFun.getText();
        setorFun = txt_setorFun.getText();
        rgFun = txt_rgFun.getText();
        cpfFun = txt_cpfFun.getText();
        cepFun = txt_cepFun.getText();
        numFun = txtNumFun.getText();
        telFun = txt_telFun.getText();
        celFun = txt_celFun.getText();

        sexoFun = cmb_sexoFun.getSelectedItem().toString();
        System.out.println(sexoFun);

        if(sexoFun.equals("-")){
            JOptionPane.showMessageDialog(null, "Escolha o sexo");
        }
        else{
        
         if (CPF.isValido(cpfFun) == false || "111.111.111-11".equals(cpfFun) || "000.000.000-00".equals(cpfFun) || "   .   .   -  ".equals(cpfFun)  ){
         
             JOptionPane.showMessageDialog(null, "Cpf Invalido");
             
             
         }
        
             else {
             
             ba.gravaFuncionario(nomeFun, nasciFun, endeFun, compleFun, bairroFun , cidadeFun, setorFun, sexoFun, rgFun, cpfFun, cepFun, numFun, telFun, celFun,ufFun);

            txt_nomeFun.setText("");
            txt_cpfFun.setText("");
            txt_rgFun.setText("");
            txt_nasciFun.setText("");
            txt_endeFun.setText("");
            txtCompleFun.setText("");
            txt_bairroFun.setText("");
            txt_cepFun.setText("");
            txtNumFun.setText("");
            txt_telFun.setText("");
            txt_celFun.setText("");
            txt_setorFun.setText("");
            txt_cidadeFun.setText("");
            txt_estadoFun.setText("");
         
        }
      }
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void btnAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFuncionarioActionPerformed

         String aux,nomeFun, nasciFun, endeFun, compleFun, bairroFun , cidadeFun, setorFun, loginFun, senhaFun, sexoFun,
        rgFun, cpfFun, cepFun, numFun,ufFun, telFun, celFun, permissao = "";

      
       
        nomeFun = txt_nomeFun.getText();
        nasciFun = txt_nasciFun.getText();
        endeFun = txt_endeFun.getText();
        compleFun = txtCompleFun.getText();
        bairroFun = txt_bairroFun.getText();
        ufFun = txt_estadoFun.getText();
        cidadeFun = txt_cidadeFun.getText();
        setorFun = txt_setorFun.getText();
        rgFun = txt_rgFun.getText();
        cpfFun = txt_cpfFun.getText();
        cepFun = txt_cepFun.getText();
        numFun = txtNumFun.getText();
        telFun = txt_telFun.getText();
        celFun = txt_celFun.getText();
        
        sexoFun = cmb_sexoFun.getSelectedItem().toString();

        if("   .   .   -  ".equals(cpfFun)){

            JOptionPane.showMessageDialog(null,"Preecha  o campo cpf");
            txt_cpfFun.requestFocus();
        }
        else{

            ba.atualizaFuncionario(nomeFun, nasciFun, endeFun, compleFun, bairroFun, ufFun,cidadeFun, setorFun, rgFun,cpfFun, cepFun, numFun, telFun, celFun,sexoFun);

        }
        
    }//GEN-LAST:event_btnAlterarFuncionarioActionPerformed

    private void txt_setorFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_setorFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_setorFunActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
          //String nomeFantasia = nome_fantasiaFor.getText();
        
       
            
             
        String cpf =txt_cpfFun.getText();

        if(CPF.isValido(cpf) == false ||"   .   .   -  ".equals(cpf)){

            JOptionPane.showMessageDialog(null,"Preencha o campo CPF  corretamente para realizar uma exclusão");
            
            txt_cpfFun.requestFocus();

        }

        else{
            if (ba.excluiUsuario(cpf)) {
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");

             txt_nomeFun.setText("");
            txt_cpfFun.setText("");
            txt_rgFun.setText("");
            txt_nasciFun.setText("");
            txt_endeFun.setText("");
            txtCompleFun.setText("");
            txt_bairroFun.setText("");
            txt_cepFun.setText("");
            txtNumFun.setText("");
            txt_telFun.setText("");
            txt_celFun.setText("");
            txt_setorFun.setText("");
            txt_cidadeFun.setText("");
            txt_estadoFun.setText("");

            }
            else {
                JOptionPane.showMessageDialog(null, "Não encontrado");
            }
        }
        
        
        
         
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
         ResultSet rs;

        
        String cpf = txt_cpfFun.getText();
        String sexoFun = null;
       

        
        if("   .   .   -  ".equals(cpf)){

            JOptionPane.showMessageDialog(null,"Preencha o campo Cpf para realizar uma busca");
            txt_cpfFun.requestFocus();
        }

        else{

            rs = ba.buscaFuncionario(cpf);
            try {

                if (ba.buscaFuncionario(cpf) != null) {
                    txt_rgFun.setText(rs.getString("rgFun"));
                    txt_nomeFun.setText(rs.getString("nomeFun"));
                    txt_setorFun.setText(rs.getString("setorFun"));
                    txt_nasciFun.setText(rs.getString("nasciFun"));
                    txt_cepFun.setText(rs.getString("cepFun"));
                    txt_estadoFun.setText(rs.getString("ufFun"));
                    txt_cidadeFun.setText(rs.getString("cidadeFun"));
                    txt_bairroFun.setText(rs.getString("bairroFun"));
                    txt_endeFun.setText(rs.getString("endeFun"));
                    txtCompleFun.setText(rs.getString("compleFun"));
                    txtNumFun.setText(rs.getString("numFun"));
                    txt_cpfFun.setText(txt_cpfFun.getText());
                    txt_telFun.setText(rs.getString("telFun"));
                     txt_celFun.setText(rs.getString("celFun"));    
                    sexoFun = rs.getString("sexoFun");
                    
                  
                     cmb_sexoFun.setSelectedItem(sexoFun);
                    
                    
                }
                
             
                else{

                    txt_rgFun.setText("");
                    txt_nomeFun.setText("");
                    txt_setorFun.setText("");
                    txt_nasciFun.setText("");
                    txt_cepFun.setText("");
                    txt_estadoFun.setText("");
                    txt_cidadeFun.setText("");
                    txt_bairroFun.setText("");
                    txt_endeFun.setText("");
                    txtCompleFun.setText("");
                    txtNumFun.setText("");
                    txt_cpfFun.setText("");
                    txt_telFun.setText("");
                     txt_celFun.setText("");   
                }
            } catch (SQLException ex) {
            }
        }
        
        
    
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
            txt_nomeFun.setText("");
            txt_cpfFun.setText("");
            txt_rgFun.setText("");
            txt_nasciFun.setText("");
            txt_endeFun.setText("");
            txtCompleFun.setText("");
            txt_bairroFun.setText("");
            txt_cepFun.setText("");
            txtNumFun.setText("");
            txt_telFun.setText("");
            txt_celFun.setText("");
            txt_setorFun.setText("");
            txt_cidadeFun.setText("");
            txt_estadoFun.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
         DefaultTableModel modelo = (DefaultTableModel)gridFuncionario.getModel();
       
    gridFuncionario.removeAll();
    
    while(modelo.getRowCount() > 0){
        modelo.removeRow(0);
    }
    String cpf = txtPesquisa.getText();
    
    ObjetoFuncionario funcionariopesquisado = new ObjetoFuncionario();
    
     if(txtPesquisa.equals("   .   .   -  ") || CPF.isValido(cpf) == false){
         JOptionPane.showMessageDialog(null,"Entre com um cpf valido");
         
     }
     
     else{
     if(txtPesquisa.getText().isEmpty() == false){
        

      
            funcionariopesquisado = ba.buscaFuncionarioTabela(String.valueOf(cpf));
            if(funcionariopesquisado != null){
                modelo.addRow(new Object[]{
                  funcionariopesquisado.getNomeFun(),
                  funcionariopesquisado.getSexoFun(),
                  funcionariopesquisado.getCpfFun(),
                  funcionariopesquisado.getRgFun(),
                  funcionariopesquisado.getNasciFun(),
                  funcionariopesquisado.getUfFun(),
                  funcionariopesquisado.getCidadeFun(),
                  funcionariopesquisado.getEndeFun(),
                  funcionariopesquisado.getBairroFun(),
                  funcionariopesquisado.getCepFun(),
                  funcionariopesquisado.getNumFun(),
                  funcionariopesquisado.getCompleFun(),
                  funcionariopesquisado.getTelFun(),
                  funcionariopesquisado.getCelFun(),
                  funcionariopesquisado.getSetorFun()
                
                
                });
            }
            else{
                JOptionPane.showMessageDialog(null, "Nenhum Cliente encontrado !!!");
            }
        
    }
  }
    gridFuncionario.repaint();
    
    txtPesquisa.setText(null);
              
    }//GEN-LAST:event_btnPesquisaActionPerformed

        // PEGA OS CAMPOS QUE ESTÃO NA JTABLE E JOGA NOS TEXTFIELDS
    
    private void gridFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridFuncionarioMouseClicked
        
        
        if (evt.getClickCount() == 2) {  
            Object obj = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 0));  //coluna 0  
            String nome = obj.toString();
           
            Object obj1 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 1));  //coluna 0  
            String sexo = obj1.toString();
            
            Object obj2 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 2));  //coluna 0  
            String cpf = obj2.toString();  
            
            Object obj3 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 3));  //coluna 0  
            String rg = obj3.toString();  
            
            Object obj4 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 4));  //coluna 0  
            String datanasci = obj4.toString();  
            
            Object obj5 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 5));  //coluna 0  
            String uf = obj5.toString(); 
            
            Object obj6 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 6));  //coluna 0  
            String cidade = obj6.toString();  
            
            Object obj7 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 7));  //coluna 0  
            String endereco = obj7.toString();  
            
            Object obj8 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 8));  //coluna 0  
            String bairro = obj8.toString();
           
            Object obj9 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 9));  //coluna 0  
            String cep = obj9.toString();  
            
            Object obj10 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 10));  //coluna 0  
            String numero = obj10.toString(); 
            
           Object obj11 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 11));  //coluna 0  
            String complemento = obj11.toString();  
           
            Object obj12 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 12));  //coluna 0  
            String telefone = obj12.toString();  
            
            Object obj13 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 13));  //coluna 0  
            String celular = obj13.toString();  
            
             Object obj14 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 14));  //coluna 0  
            String setor = obj14.toString();
            
            
         
            // SETA OS DADOS PEGO ACIMA PARA OS JTEXTFIELD

             txt_cpfFun.setText(cpf);   
             txt_rgFun.setText(rg); 
             txt_nomeFun.setText(nome); 
             txt_nasciFun.setText(datanasci); 
             txt_estadoFun.setText(uf); 
             txt_cidadeFun.setText(cidade); 
             txt_bairroFun.setText(bairro);     
             txt_endeFun.setText(endereco); 
             txtNumFun.setText(numero);
             txt_cepFun.setText(cep);       
             txtCompleFun.setText(complemento); 
             txt_setorFun.setText(setor); 
         
             txt_telFun.setText(telefone);    
             txt_celFun.setText(celular);    
              
            cmb_sexoFun.setSelectedItem(sexo);
           
             
             
             
               // QUANDO SELECIONA A LINHA NA JTABLE MUDA A ABA
              TabFuncionario.setSelectedIndex(0);   
             
        }
        
    }//GEN-LAST:event_gridFuncionarioMouseClicked

    private void cmb_sexoFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sexoFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_sexoFunActionPerformed

    
    
      private void jTextField1FocusLostCpf(java.awt.event.FocusEvent evt) {
        String cpfFor = txt_cpfFun.getText();
        String cpf = cpfFor;

            if (CPF.isValido(cpfFor) == false || "111.111.111-11".equals(cpfFor) || "000.000.000-00".equals(cpfFor) || "   .   .   -  ".equals(cpfFor)  ){


          

          JOptionPane.showMessageDialog(null,"Atenção Cpf inválido");
          
          txt_cpfFun.requestFocus();
          
          
         }
        else{
         
         ValidaCnpj.formatar(cpf);
         txt_cpfFun.setText(cpf);
         System.out.println(cpf);
         
        }

    }

      
      
       private void jTextField1FocusLostCep(java.awt.event.FocusEvent evt) {  
        ResultSet rs;

        String cep = txt_cepFun.getText();

        if("".equals(cep)){

        }

        
        else{
            
            
            rs = bacep.buscaCep(cep);
            try {

                if (bacep.buscaCep(cep) != null) {

                    txt_endeFun.setText(rs.getString("desc_logradouro"));
                    txt_cidadeFun.setText(rs.getString("desc_cidade"));
                    txt_estadoFun.setText(rs.getString("flg_estado"));
                    txt_bairroFun.setText(rs.getString("desc_bairro"));
                    
                }
                else{

                }
            } catch (SQLException ex) {
            }
        } 
        
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabFuncionario;
    private javax.swing.JButton btnAlterarFuncionario;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JComboBox cmb_sexoFun;
    private javax.swing.JTable gridFuncionario;
    public javax.swing.JInternalFrame internalFuncionario;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField txtCompleFun;
    private javax.swing.JTextField txtNumFun;
    private javax.swing.JFormattedTextField txtPesquisa;
    private javax.swing.JFormattedTextField txt_bairroFun;
    private javax.swing.JFormattedTextField txt_celFun;
    private javax.swing.JFormattedTextField txt_cepFun;
    private javax.swing.JTextField txt_cidadeFun;
    private javax.swing.JFormattedTextField txt_cpfFun;
    private javax.swing.JFormattedTextField txt_endeFun;
    private javax.swing.JTextField txt_estadoFun;
    private javax.swing.JFormattedTextField txt_nasciFun;
    private javax.swing.JFormattedTextField txt_nomeFun;
    private javax.swing.JFormattedTextField txt_rgFun;
    private javax.swing.JTextField txt_setorFun;
    private javax.swing.JFormattedTextField txt_telFun;
    // End of variables declaration//GEN-END:variables
}
