/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Caixa;

/**
 *
 * @author Usuario
 */
public class Caixa extends javax.swing.JFrame {

    /**
     * Creates new form Produtos
     */
    public Caixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalProdutos = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        internalProdutos.setClosable(true);
        internalProdutos.setVisible(true);
        internalProdutos.getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel1.setLayout(null);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(11)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(30, 40, 120, 30);

        jLabel1.setText("Ciente: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 70, 60, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 100, 470, 30);

        jLabel2.setText("Telefone");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 60, 30);

        jButton1.setText("Buscar");
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 40, 170, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(30, 160, 470, 30);

        jLabel3.setText("Endereco:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 130, 60, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 220, 470, 30);

        jLabel4.setText("Bairro:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 60, 30);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 280, 470, 30);

        jLabel5.setText("Ponto de Refêrencia:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 250, 120, 30);

        jButton3.setText("Alterar Dados do Cliente");
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 320, 170, 23);

        internalProdutos.getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 550, 360);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descricao", "Qtde", "Preco", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        internalProdutos.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 460, 1170, 200);

        jButton2.setText("Registrar Novo Cliente");
        internalProdutos.getContentPane().add(jButton2);
        jButton2.setBounds(20, 10, 150, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jLabel6.setText("Codigo Produto:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 10, 100, 30);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(120, 10, 90, 30);

        jLabel7.setText("Preço:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(180, 60, 40, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(20, 90, 150, 30);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField6);
        jTextField6.setBounds(180, 90, 70, 30);

        jLabel8.setText("Pizza/Produto:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 60, 90, 30);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(260, 90, 80, 30);

        jLabel9.setText("Qtde:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(260, 70, 28, 14);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(jTextField8);
        jTextField8.setBounds(350, 90, 80, 30);

        jLabel10.setText("Total:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(350, 60, 40, 30);

        jButton4.setText("Incluir no Pedido:");
        jPanel2.add(jButton4);
        jButton4.setBounds(160, 140, 150, 40);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizza Com 2 Sabores ou Mais:"));
        jPanel3.setLayout(null);

        jRadioButton1.setText("2 Partes");
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(10, 40, 65, 23);

        jRadioButton2.setText("3 Partes");
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(10, 70, 65, 23);

        jRadioButton3.setText("4 Partes");
        jPanel3.add(jRadioButton3);
        jRadioButton3.setBounds(10, 100, 65, 23);

        jLabel11.setText("Sabor 1:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(150, 20, 60, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(200, 20, 150, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox3);
        jComboBox3.setBounds(200, 60, 150, 30);

        jLabel12.setText("Sabor 2:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(150, 60, 60, 30);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jTextField9);
        jTextField9.setBounds(360, 20, 70, 30);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jTextField10);
        jTextField10.setBounds(240, 120, 70, 30);

        jLabel13.setText("Valor da Pizza:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(240, 90, 80, 30);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jTextField11);
        jTextField11.setBounds(360, 60, 70, 30);

        jButton5.setText("Incluir no Pedido: ");
        jPanel3.add(jButton5);
        jButton5.setBounds(380, 110, 120, 50);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(20, 200, 520, 180);

        internalProdutos.getContentPane().add(jPanel2);
        jPanel2.setBounds(570, 20, 600, 390);

        jLabel14.setText("Observação: ");
        internalProdutos.getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 690, 90, 30);
        internalProdutos.getContentPane().add(jTextField12);
        jTextField12.setBounds(10, 730, 410, 30);

        getContentPane().add(internalProdutos);
        internalProdutos.setBounds(0, 0, 1600, 900);

        setBounds(0, 0, 1616, 938);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JInternalFrame internalProdutos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
