
package Produtos;
import Banco.Banco;
import BancoObjeto.ObjetoCategoriaProduto;
import BancoObjeto.ObjetoCliente;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class Produtos extends javax.swing.JFrame {

    Banco ba = new Banco();
    
    public Produtos() {
        initComponents();
        
 
            
      gridCategoriaProduto.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"Nome Categoria" }) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }});  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalProduto = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        Gravar = new javax.swing.JButton();
        Pesquisar = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtCategoriaProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridCategoriaProduto = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        Novo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        Gravar1 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        Alterar = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        Excluir = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        Pesquisar1 = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        internalProduto.setClosable(true);
        internalProduto.setVisible(true);
        internalProduto.getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jToolBar1.setFloatable(false);

        Gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        Gravar.setText("Registrar");
        Gravar.setFocusable(false);
        Gravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Gravar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Gravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarActionPerformed(evt);
            }
        });
        jToolBar1.add(Gravar);

        Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        Pesquisar.setText("Pesquisar");
        Pesquisar.setFocusable(false);
        Pesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pesquisar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Pesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(Pesquisar);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton19.setText("Excluir");
        jButton19.setFocusable(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton19);

        jPanel1.add(jToolBar1);
        jToolBar1.setBounds(0, 0, 720, 70);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel4.setLayout(null);
        jPanel4.add(txtCategoriaProduto);
        txtCategoriaProduto.setBounds(70, 40, 140, 30);

        jLabel1.setText("Categoria:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(10, 40, 70, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 70, 250, 100);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros Categoria"));
        jPanel5.setLayout(null);

        gridCategoriaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gridCategoriaProduto);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 740, 280);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 180, 760, 310);

        jTabbedPane1.addTab("Registrar Categoria", jPanel1);

        jPanel2.setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(null);

        jRadioButton1.setText("Produto Acabado");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton1);
        jRadioButton1.setBounds(10, 30, 130, 23);

        jRadioButton2.setText("Materia Prima");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton2);
        jRadioButton2.setBounds(140, 30, 110, 23);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 330, 260, 80);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(null);
        jPanel7.add(jTextField4);
        jTextField4.setBounds(80, 40, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Valor:");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(30, 40, 40, 30);

        jCheckBox1.setText("Produto de Venda:");
        jPanel7.add(jCheckBox1);
        jCheckBox1.setBounds(50, 10, 130, 23);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(280, 330, 230, 80);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Ingredientes: ");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(20, 100, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Descrição: ");
        jPanel8.add(jLabel2);
        jLabel2.setBounds(20, 50, 68, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tipo Produto: ");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(20, 10, 80, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um tipo de produto" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBox1);
        jComboBox1.setBounds(100, 10, 190, 30);
        jPanel8.add(jTextField1);
        jTextField1.setBounds(100, 50, 420, 30);
        jPanel8.add(jTextField2);
        jTextField2.setBounds(100, 100, 420, 30);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(10, 90, 690, 160);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Unid. Medida: ");
        jPanel9.add(jLabel5);
        jLabel5.setBounds(30, 10, 100, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UN", "KG", "CX", "DZ", "GR", "LT" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox2);
        jComboBox2.setBounds(130, 10, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Estocavél:");
        jPanel9.add(jLabel6);
        jLabel6.setBounds(240, 10, 55, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "SIM", "NAO" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox3);
        jComboBox3.setBounds(310, 10, 70, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Qtde. Minima Estoque:");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(410, 10, 140, 30);
        jPanel9.add(jTextField3);
        jTextField3.setBounds(560, 10, 90, 30);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(10, 260, 690, 50);
        jPanel2.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(620, 360, 80, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Data Registro: ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(520, 360, 90, 30);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        Novo.setText("Novo");
        Novo.setFocusable(false);
        Novo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Novo.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Novo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        jToolBar2.add(Novo);
        jToolBar2.add(jSeparator1);

        Gravar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        Gravar1.setText("Gravar");
        Gravar1.setFocusable(false);
        Gravar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Gravar1.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Gravar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Gravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gravar1ActionPerformed(evt);
            }
        });
        jToolBar2.add(Gravar1);
        jToolBar2.add(jSeparator7);

        Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        Alterar.setText("Alterar");
        Alterar.setFocusable(false);
        Alterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Alterar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Alterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        jToolBar2.add(Alterar);
        jToolBar2.add(jSeparator10);

        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        Excluir.setText("Excluir");
        Excluir.setFocusable(false);
        Excluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Excluir.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Excluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jToolBar2.add(Excluir);
        jToolBar2.add(jSeparator16);

        Pesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        Pesquisar1.setText("Pesquisar");
        Pesquisar1.setFocusable(false);
        Pesquisar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pesquisar1.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Pesquisar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Pesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisar1ActionPerformed(evt);
            }
        });
        jToolBar2.add(Pesquisar1);
        jToolBar2.add(jSeparator14);

        jPanel2.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 780, 80);

        jTabbedPane1.addTab("Registrar Produto", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        internalProduto.getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 790, 580);

        getContentPane().add(internalProduto);
        internalProduto.setBounds(10, 0, 800, 610);

        setBounds(0, 0, 842, 656);
    }// </editor-fold>//GEN-END:initComponents

    private void GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarActionPerformed
   
        /*SE A PESSOA FOR FISICA FAZ A INSERÇÃO NO BANCO É O MESMO CODIGO DE BAIXO*/

        String categoria;

        categoria = txtCategoriaProduto.getText();
  

        if("".equals(txtCategoriaProduto) ){

            JOptionPane.showMessageDialog(null," Preenche o campo categoria");

        }

        else{
            ba.gravarCategoriaProduto(categoria);

            txtCategoriaProduto.setText("");
     
        }

    }//GEN-LAST:event_GravarActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
     DefaultTableModel modelo = (DefaultTableModel)gridCategoriaProduto.getModel();
       
    gridCategoriaProduto.removeAll();
    
    while(modelo.getRowCount() > 0){
        modelo.removeRow(0);
    }
    
    ObjetoCategoriaProduto categoriapesquisada = new ObjetoCategoriaProduto();
         String  categoria = txtCategoriaProduto.getText();
  
    
     if(txtCategoriaProduto.equals("")){
        
         
     }

       else{
            categoriapesquisada = ba.buscaCategoriaProdutoTabela(String.valueOf(categoria));
            if(categoriapesquisada != null){
                modelo.addRow(new Object[]{categoriapesquisada.getCategoria()});
            }
            else{
                JOptionPane.showMessageDialog(null, "Nenhuma categoria encontrado !!!");
            }
        }
    
    
    gridCategoriaProduto.repaint();
    
    txtCategoriaProduto.setText(null);
    
    

    }//GEN-LAST:event_PesquisarActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
      
  //String nomeFantasia = nome_fantasiaFor.getText();

        String categoria =txtCategoriaProduto.getText();

        if(txtCategoriaProduto.equals("")){

            JOptionPane.showMessageDialog(null,"Preencha o campo categoria para realizar uma exclusão");

            txtCategoriaProduto.requestFocus();

        }

        else{
            if (ba.excluiCategoriaProduto(categoria)) {
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");

                txtCategoriaProduto.setText("");
              

            }
            else {
                JOptionPane.showMessageDialog(null, "Não encontrado");
            }
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed

    }//GEN-LAST:event_NovoActionPerformed

    private void Gravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gravar1ActionPerformed
       
    }//GEN-LAST:event_Gravar1ActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed

    }//GEN-LAST:event_AlterarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExcluirActionPerformed

    private void Pesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisar1ActionPerformed
     
    }//GEN-LAST:event_Pesquisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Gravar;
    private javax.swing.JButton Gravar1;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton Pesquisar1;
    private javax.swing.JTable gridCategoriaProduto;
    public javax.swing.JInternalFrame internalProduto;
    private javax.swing.JButton jButton19;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField txtCategoriaProduto;
    // End of variables declaration//GEN-END:variables
}
